### ISSUE TITLE
1.3 + npm compatible ?

### ISSUE THREAD

**Issue by Devidian** [barbatus/ng2-meteor-accounts#7]
is `ng2-meteor-accounts` and `ng2-meteor-accounts-ui` npm compatible with meteor 1.3-rc.4+?

(I just tried and its not working on my site - because its installing athmosphere packages)

For now i will remove those packages from my current project code and try getting a workaround.

**Comment by studiollama** [comment]
I also experience this not working.

**Comment by barbatus** [comment]
No, they are not compatible with Meteor 1.3.
There is new `accounts-ui` NPM for Meteor 1.3 that is under development now https://github.com/Urigo/angular2-meteor-accounts-ui. `ng2-meteor-accounts` NPM will likely be created soon too.

**Comment by Devidian** [comment]
ok great, added it. My current workaround for inject user doesn't seem to do a good job all the time :D i will keep an eye on this.

**Comment by slippyC** [comment]
Devidian, does this have to do with the `Meteor.user()` or `user` still being null?  If this is the case, it is because the Meteor users collection going on in the background is not yet ready.

An easy way to deal with this is to do a check on this:
`Meteor.status().connected`

This returns true or false when the data is ready(this is tied to your user data).

**Comment by barbatus** [comment]
relative https://github.com/Urigo/angular2-meteor-auto-bootstrap/issues/2#issuecomment-212598458

**Comment by slippyC** [comment]
Basically the way I dealt with it was using `Meteor.wrapAsync` which called a function with a `Meteor.setInteval` timer.  Had this fire every 50ms to check the status of `Meteor.status().connected`.  After that it called a function that started loading databases I needed.  In the function that was loading the databases I had a handle to the id of the timer.  Then just killed the timer off.
